//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzPos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EzPos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Ambulance32 {
            get {
                object obj = ResourceManager.GetObject("Ambulance32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string AppParamReceiptFooter {
            get {
                return ResourceManager.GetString("AppParamReceiptFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        internal static string AppParamServerPhotoPath {
            get {
                return ResourceManager.GetString("AppParamServerPhotoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string AppParamShopAddress {
            get {
                return ResourceManager.GetString("AppParamShopAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        internal static string AppParamShopContact {
            get {
                return ResourceManager.GetString("AppParamShopContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string AppParamShopName {
            get {
                return ResourceManager.GetString("AppParamShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បារកូដ.
        /// </summary>
        internal static string BarCodeValue {
            get {
                return ResourceManager.GetString("BarCodeValue", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap bg_black {
            get {
                object obj = ResourceManager.GetObject("bg_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg_black_line_top {
            get {
                object obj = ResourceManager.GetObject("bg_black_line_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg_mouse_enter {
            get {
                object obj = ResourceManager.GetObject("bg_mouse_enter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg_mouse_leave {
            get {
                object obj = ResourceManager.GetObject("bg_mouse_leave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Binoc32 {
            get {
                object obj = ResourceManager.GetObject("Binoc32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon BlackServer {
            get {
                object obj = ResourceManager.GetObject("BlackServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Books32 {
            get {
                object obj = ResourceManager.GetObject("Books32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel32 {
            get {
                object obj = ResourceManager.GetObject("Cancel32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Computer32 {
            get {
                object obj = ResourceManager.GetObject("Computer32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Config32 {
            get {
                object obj = ResourceManager.GetObject("Config32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Contract32 {
            get {
                object obj = ResourceManager.GetObject("Contract32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap customer32 {
            get {
                object obj = ResourceManager.GetObject("customer32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Database32 {
            get {
                object obj = ResourceManager.GetObject("Database32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon DataServer {
            get {
                object obj = ResourceManager.GetObject("DataServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ថ្ងៃផុតកំណត់.
        /// </summary>
        internal static string DateExpire {
            get {
                return ResourceManager.GetString("DateExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ថ្ងៃទិញចូល.
        /// </summary>
        internal static string DateIn {
            get {
                return ResourceManager.GetString("DateIn", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Delete32 {
            get {
                object obj = ResourceManager.GetObject("Delete32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon DesableServer {
            get {
                object obj = ResourceManager.GetObject("DesableServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon DownloadServer {
            get {
                object obj = ResourceManager.GetObject("DownloadServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon EmailServer {
            get {
                object obj = ResourceManager.GetObject("EmailServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon EnableServer {
            get {
                object obj = ResourceManager.GetObject("EnableServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit32 {
            get {
                object obj = ResourceManager.GetObject("exit32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Favorites32 {
            get {
                object obj = ResourceManager.GetObject("Favorites32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon FirewallServer {
            get {
                object obj = ResourceManager.GetObject("FirewallServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Info32 {
            get {
                object obj = ResourceManager.GetObject("Info32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទីតាំង.
        /// </summary>
        internal static string LocationID {
            get {
                return ResourceManager.GetString("LocationID", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon LockServer {
            get {
                object obj = ResourceManager.GetObject("LockServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string MessageCaptionConfirm {
            get {
                return ResourceManager.GetString("MessageCaptionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageCaptionError {
            get {
                return ResourceManager.GetString("MessageCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MessageCaptionInformation {
            get {
                return ResourceManager.GetString("MessageCaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error detected.
        /// </summary>
        internal static string MessageCaptionUnknownError {
            get {
                return ResourceManager.GetString("MessageCaptionUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string MsgCaptionUnknownError {
            get {
                return ResourceManager.GetString("MsgCaptionUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទំនាក់ទំនងជាមួយម៉ាស៊ីនមេ ត្រូវបានកាត់ផ្ដាច់។ សូម​មេត្តា​ទាក់ទង​​ជាមួយ​អ្នក​ទទួល​ខុស​ត្រូវ​៕.
        /// </summary>
        internal static string MsgConnectionLost {
            get {
                return ResourceManager.GetString("MsgConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ម៉ាស៊ីន​នេះ​មិន​មាន​សិទ្ឋិ​ចូល​ទៅ​ក្នុង​ប្រព័ន្ឋ​ទេ​។ សូម​មេត្តា​ទាក់ទង​​ជាមួយ​អ្នក​ទទួល​ខុស​ត្រូវ​៕.
        /// </summary>
        internal static string MsgCounterNotInitialize {
            get {
                return ResourceManager.GetString("MsgCounterNotInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ពត៌មានដែលអ្នកបានបញ្ចូលពុំត្រឹមត្រូវ។ សូមមេត្តាត្រួតពិនិត្យឡើងវិញ !.
        /// </summary>
        internal static string MsgInvalidData {
            get {
                return ResourceManager.GetString("MsgInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមអភ័យទោស ផលិតផលនេះពុំអាចលក់ជូនក្នុងតំលៃនេះបានទេ។ សូមមេត្តាព្យាយាម្ដងទៀតជាមួយតំលៃដែលខ្ពស់ជាងនេះ៕.
        /// </summary>
        internal static string MsgInvalidUnitPriceOut {
            get {
                return ResourceManager.GetString("MsgInvalidUnitPriceOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item specified does not exist in the list..
        /// </summary>
        internal static string MsgItemNotInList {
            get {
                return ResourceManager.GetString("MsgItemNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អ្នកកំពុងព្យាយាមយកផលិតផលមួយចំនួនទៅដាក់ក្នុងស្តុក។ ប្រតិបត្តិការនេះអាចនឹងចំណាយពេលយូរ ៕.
        /// </summary>
        internal static string MsgOperationImportGroupCatalog {
            get {
                return ResourceManager.GetString("MsgOperationImportGroupCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូម​មេត្តា​ចុច​លើ​ប៊ូតុង យល់​ព្រម ដើម្បី​បញ្ជាក់​អំពី​សំណើរ​បោះ​បង់​របស់​អ្នក ។.
        /// </summary>
        internal static string MsgOperationRequestCancel {
            get {
                return ResourceManager.GetString("MsgOperationRequestCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ពុំមានអតិថិជនដែលអ្នកស្វែងរកទេ ។ សូមព្យាយាមម្ដងទៀត !.
        /// </summary>
        internal static string MsgOperationRequestCustomerNotFound {
            get {
                return ResourceManager.GetString("MsgOperationRequestCustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to តើអ្នកពិតជាចង់លុប .
        /// </summary>
        internal static string MsgOperationRequestDelete {
            get {
                return ResourceManager.GetString("MsgOperationRequestDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូម​មេត្តា​ចុច​លើ​ប៊ូតុង យល់​ព្រម ដើម្បី​ដក​ហូត​ប័ណ្ណ​បញ្ចុះ​តំលៃ​ពី .
        /// </summary>
        internal static string MsgOperationRequestGetBackCard {
            get {
                return ResourceManager.GetString("MsgOperationRequestGetBackCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឈ្មោះ រឺ ពាក្យសំងាត់ដែលអ្នកបានបញ្ចូលពុំត្រឹមត្រូវទេ។ សូមមេត្តាត្រួតពិនិត្យឡើងវិញ !.
        /// </summary>
        internal static string MsgOperationRequestLogInFail {
            get {
                return ResourceManager.GetString("MsgOperationRequestLogInFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ពុំមានផលិតផលដែលអ្នកស្វែងរកទេ ។ សូមព្យាយាមម្ដងទៀត !.
        /// </summary>
        internal static string MsgOperationRequestProductNotFound {
            get {
                return ResourceManager.GetString("MsgOperationRequestProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ផលិតផលនេះពុំអាចលុបបានទេ។ សូមមេត្តាទាក់ទងអ្នកទទួលខុសត្រូវ៕.
        /// </summary>
        internal static string MsgUnknownError {
            get {
                return ResourceManager.GetString("MsgUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អ្នក​ពុំ​មាន​សិទ្ឋិ​គ្រប់​គ្រាន់​សំរាប់​ប្រតិបត្តិ​ការ​នេះ​ទេ ។.
        /// </summary>
        internal static string MsgUserPermissionDeny {
            get {
                return ResourceManager.GetString("MsgUserPermissionDeny", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap News32 {
            get {
                object obj = ResourceManager.GetObject("News32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OK32 {
            get {
                object obj = ResourceManager.GetObject("OK32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEL.
        /// </summary>
        internal static string OperationRequestDelete {
            get {
                return ResourceManager.GetString("OperationRequestDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPL.
        /// </summary>
        internal static string OperationRequestDuplicate {
            get {
                return ResourceManager.GetString("OperationRequestDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS.
        /// </summary>
        internal static string OperationRequestInsert {
            get {
                return ResourceManager.GetString("OperationRequestInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD.
        /// </summary>
        internal static string OperationRequestUpdate {
            get {
                return ResourceManager.GetString("OperationRequestUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVNOPT.
        /// </summary>
        internal static string PermissionAVNOPT {
            get {
                return ResourceManager.GetString("PermissionAVNOPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRCPRN.
        /// </summary>
        internal static string PermissionBRCPRN {
            get {
                return ResourceManager.GetString("PermissionBRCPRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRWRPT.
        /// </summary>
        internal static string PermissionBRWRPT {
            get {
                return ResourceManager.GetString("PermissionBRWRPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANSAL.
        /// </summary>
        internal static string PermissionCANSAL {
            get {
                return ResourceManager.GetString("PermissionCANSAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSMNG.
        /// </summary>
        internal static string PermissionCUSMNG {
            get {
                return ResourceManager.GetString("PermissionCUSMNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELSAL.
        /// </summary>
        internal static string PermissionDELSAL {
            get {
                return ResourceManager.GetString("PermissionDELSAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCRAT.
        /// </summary>
        internal static string PermissionEXCRAT {
            get {
                return ResourceManager.GetString("PermissionEXCRAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LABMNG.
        /// </summary>
        internal static string PermissionLABMNG {
            get {
                return ResourceManager.GetString("PermissionLABMNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCMNG.
        /// </summary>
        internal static string PermissionLOCMNG {
            get {
                return ResourceManager.GetString("PermissionLOCMNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDFSAL.
        /// </summary>
        internal static string PermissionMDFSAL {
            get {
                return ResourceManager.GetString("PermissionMDFSAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGMNG.
        /// </summary>
        internal static string PermissionORGMNG {
            get {
                return ResourceManager.GetString("PermissionORGMNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCOMNG.
        /// </summary>
        internal static string PermissionPCOMNG {
            get {
                return ResourceManager.GetString("PermissionPCOMNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRDCAT.
        /// </summary>
        internal static string PermissionPRDCAT {
            get {
                return ResourceManager.GetString("PermissionPRDCAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRDMNG.
        /// </summary>
        internal static string PermissionPRDMNG {
            get {
                return ResourceManager.GetString("PermissionPRDMNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRDUNT.
        /// </summary>
        internal static string PermissionPRDUNT {
            get {
                return ResourceManager.GetString("PermissionPRDUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCDSAL.
        /// </summary>
        internal static string PermissionRCDSAL {
            get {
                return ResourceManager.GetString("PermissionRCDSAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPMNG.
        /// </summary>
        internal static string PermissionSUPMNG {
            get {
                return ResourceManager.GetString("PermissionSUPMNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USRMNG.
        /// </summary>
        internal static string PermissionUSRMNG {
            get {
                return ResourceManager.GetString("PermissionUSRMNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VUWSAL.
        /// </summary>
        internal static string PermissionVUWSAL {
            get {
                return ResourceManager.GetString("PermissionVUWSAL", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Pill32 {
            get {
                object obj = ResourceManager.GetObject("Pill32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon PrintServer {
            get {
                object obj = ResourceManager.GetObject("PrintServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Product32 {
            get {
                object obj = ResourceManager.GetObject("Product32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឯកតា.
        /// </summary>
        internal static string ProductUnitID {
            get {
                return ResourceManager.GetString("ProductUnitID", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon ProxyServer {
            get {
                object obj = ResourceManager.GetObject("ProxyServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap purchase {
            get {
                object obj = ResourceManager.GetObject("purchase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purchase32 {
            get {
                object obj = ResourceManager.GetObject("Purchase32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បរិមាណ.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon RemoveServer {
            get {
                object obj = ResourceManager.GetObject("RemoveServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sale32 {
            get {
                object obj = ResourceManager.GetObject("Sale32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search32 {
            get {
                object obj = ResourceManager.GetObject("Search32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon SearchServer {
            get {
                object obj = ResourceManager.GetObject("SearchServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon server {
            get {
                object obj = ResourceManager.GetObject("server", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SnakeCup32 {
            get {
                object obj = ResourceManager.GetObject("SnakeCup32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Text32 {
            get {
                object obj = ResourceManager.GetObject("Text32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Undo32 {
            get {
                object obj = ResourceManager.GetObject("Undo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to តំលៃឯកតា.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon UnlockServer {
            get {
                object obj = ResourceManager.GetObject("UnlockServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon UploadServer {
            get {
                object obj = ResourceManager.GetObject("UploadServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User32 {
            get {
                object obj = ResourceManager.GetObject("User32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wait32 {
            get {
                object obj = ResourceManager.GetObject("Wait32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon WebServer {
            get {
                object obj = ResourceManager.GetObject("WebServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
