//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzPos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EzPos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add32 {
            get {
                object obj = ResourceManager.GetObject("add32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string AppParamCategory {
            get {
                return ResourceManager.GetString("AppParamCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string AppParamColor {
            get {
                return ResourceManager.GetString("AppParamColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string AppParamContractType {
            get {
                return ResourceManager.GetString("AppParamContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string AppParamCountry {
            get {
                return ResourceManager.GetString("AppParamCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string AppParamCourteousy {
            get {
                return ResourceManager.GetString("AppParamCourteousy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string AppParamCurrency {
            get {
                return ResourceManager.GetString("AppParamCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string AppParamDiscountType {
            get {
                return ResourceManager.GetString("AppParamDiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterLabel.
        /// </summary>
        internal static string AppParamDisplay {
            get {
                return ResourceManager.GetString("AppParamDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string AppParamExchangeRate {
            get {
                return ResourceManager.GetString("AppParamExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string AppParamExpense {
            get {
                return ResourceManager.GetString("AppParamExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string AppParamFeature {
            get {
                return ResourceManager.GetString("AppParamFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string AppParamGender {
            get {
                return ResourceManager.GetString("AppParamGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string AppParamMaritalStatus {
            get {
                return ResourceManager.GetString("AppParamMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string AppParamMark {
            get {
                return ResourceManager.GetString("AppParamMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string AppParamPaymentType {
            get {
                return ResourceManager.GetString("AppParamPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string AppParamPosition {
            get {
                return ResourceManager.GetString("AppParamPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string AppParamPOStatus {
            get {
                return ResourceManager.GetString("AppParamPOStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string AppParamProductCodeLength {
            get {
                return ResourceManager.GetString("AppParamProductCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string AppParamReceiptFooter {
            get {
                return ResourceManager.GetString("AppParamReceiptFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        internal static string AppParamReceiptPrinter {
            get {
                return ResourceManager.GetString("AppParamReceiptPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string AppParamReportPrinter {
            get {
                return ResourceManager.GetString("AppParamReportPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        internal static string AppParamServerPhotoPath {
            get {
                return ResourceManager.GetString("AppParamServerPhotoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string AppParamShopAddress {
            get {
                return ResourceManager.GetString("AppParamShopAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        internal static string AppParamShopContact {
            get {
                return ResourceManager.GetString("AppParamShopContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string AppParamShopName {
            get {
                return ResourceManager.GetString("AppParamShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string AppParamSize {
            get {
                return ResourceManager.GetString("AppParamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string AppParamSkin {
            get {
                return ResourceManager.GetString("AppParamSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterID.
        /// </summary>
        internal static string AppParamValue {
            get {
                return ResourceManager.GetString("AppParamValue", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap b_drop {
            get {
                object obj = ResourceManager.GetObject("b_drop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backgroud_11 {
            get {
                object obj = ResourceManager.GetObject("backgroud_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backgroud_12 {
            get {
                object obj = ResourceManager.GetObject("backgroud_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background_16 {
            get {
                object obj = ResourceManager.GetObject("background_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background_2 {
            get {
                object obj = ResourceManager.GetObject("background_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background_5 {
            get {
                object obj = ResourceManager.GetObject("background_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background_9 {
            get {
                object obj = ResourceManager.GetObject("background_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Buy32 {
            get {
                object obj = ResourceManager.GetObject("Buy32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel32 {
            get {
                object obj = ResourceManager.GetObject("Cancel32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Config32 {
            get {
                object obj = ResourceManager.GetObject("Config32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customer32 {
            get {
                object obj = ResourceManager.GetObject("Customer32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete32 {
            get {
                object obj = ResourceManager.GetObject("Delete32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit32 {
            get {
                object obj = ResourceManager.GetObject("exit32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string MessageCaptionConfirm {
            get {
                return ResourceManager.GetString("MessageCaptionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageCaptionError {
            get {
                return ResourceManager.GetString("MessageCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MessageCaptionInformation {
            get {
                return ResourceManager.GetString("MessageCaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error detected.
        /// </summary>
        internal static string MessageCaptionUnknownError {
            get {
                return ResourceManager.GetString("MessageCaptionUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string ModCustomer {
            get {
                return ResourceManager.GetString("ModCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer debt.
        /// </summary>
        internal static string ModCustomerDebt {
            get {
                return ResourceManager.GetString("ModCustomerDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount card.
        /// </summary>
        internal static string ModDiscountCard {
            get {
                return ResourceManager.GetString("ModDiscountCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string MsgCaptionConfirm {
            get {
                return ResourceManager.GetString("MsgCaptionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MsgCaptionError {
            get {
                return ResourceManager.GetString("MsgCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MsgCaptionInformation {
            get {
                return ResourceManager.GetString("MsgCaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string MsgCaptionUnknownError {
            get {
                return ResourceManager.GetString("MsgCaptionUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input amount is less then due amount. Do you want to proceed ?.
        /// </summary>
        internal static string MsgConfirmCreditPayment {
            get {
                return ResourceManager.GetString("MsgConfirmCreditPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ផលិតផលដូចគ្នានឹងលេខកូដនេះត្រូវបានរកឃើញ​។ តើអ្នកចង់កែប្រែពត៌មាននៃផលិតផលដែលបានរកឃើញ?.
        /// </summary>
        internal static string MsgConfirmEditExistingProduct {
            get {
                return ResourceManager.GetString("MsgConfirmEditExistingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទំនាក់ទំនងជាមួយម៉ាស៊ីនមេ ត្រូវបានកាត់ផ្ដាច់។ សូម​មេត្តា​ទាក់ទង​​ជាមួយ​អ្នក​ទទួល​ខុស​ត្រូវ​៕.
        /// </summary>
        internal static string MsgConnectionLost {
            get {
                return ResourceManager.GetString("MsgConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ម៉ាស៊ីន​នេះ​មិន​មាន​សិទ្ឋិ​ចូល​ទៅ​ក្នុង​ប្រព័ន្ឋ​ទេ​។ សូម​មេត្តា​ទាក់ទង​​ជាមួយ​អ្នក​ទទួល​ខុស​ត្រូវ​៕.
        /// </summary>
        internal static string MsgCounterNotInitialize {
            get {
                return ResourceManager.GetString("MsgCounterNotInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to លេខកូដផលិតផលដែលបានបញ្ចូលពុំត្រឹមត្រូវទេ។ សូមមេត្តាត្រួតពិនិត្យឡើងវិញ !.
        /// </summary>
        internal static string MsgExceedProductCodeLength {
            get {
                return ResourceManager.GetString("MsgExceedProductCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ពត៌មានដែលអ្នកបានបញ្ចូលពុំត្រឹមត្រូវ។ សូមមេត្តាត្រួតពិនិត្យឡើងវិញ !.
        /// </summary>
        internal static string MsgInvalidData {
            get {
                return ResourceManager.GetString("MsgInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមអភ័យទោស ផលិតផលនេះពុំអាចលក់ជូនក្នុងតំលៃនេះបានទេ។ សូមមេត្តាព្យាយាម្ដងទៀតជាមួយតំលៃដែលខ្ពស់ជាងនេះ៕.
        /// </summary>
        internal static string MsgInvalidUnitPriceOut {
            get {
                return ResourceManager.GetString("MsgInvalidUnitPriceOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item specified does not exist in the list..
        /// </summary>
        internal static string MsgItemNotInList {
            get {
                return ResourceManager.GetString("MsgItemNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អ្នកកំពុងព្យាយាមយកផលិតផលមួយចំនួនទៅដាក់ក្នុងស្តុក។ ប្រតិបត្តិការនេះអាចនឹងចំណាយពេលយូរ ៕.
        /// </summary>
        internal static string MsgOperationImportGroupCatalog {
            get {
                return ResourceManager.GetString("MsgOperationImportGroupCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូម​មេត្តា​ចុច​លើ​ប៊ូតុង យល់​ព្រម ដើម្បី​បញ្ជាក់​អំពី​សំណើរ​បោះ​បង់​របស់​អ្នក ។.
        /// </summary>
        internal static string MsgOperationRequestCancel {
            get {
                return ResourceManager.GetString("MsgOperationRequestCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ពុំមានអតិថិជនដែលអ្នកស្វែងរកទេ ។ សូមព្យាយាមម្ដងទៀត !.
        /// </summary>
        internal static string MsgOperationRequestCustomerNotFound {
            get {
                return ResourceManager.GetString("MsgOperationRequestCustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to តើអ្នកពិតជាចង់លុប .
        /// </summary>
        internal static string MsgOperationRequestDelete {
            get {
                return ResourceManager.GetString("MsgOperationRequestDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូម​មេត្តា​ចុច​លើ​ប៊ូតុង យល់​ព្រម ដើម្បី​ដក​ហូត​ប័ណ្ណ​បញ្ចុះ​តំលៃ​ពី .
        /// </summary>
        internal static string MsgOperationRequestGetBackCard {
            get {
                return ResourceManager.GetString("MsgOperationRequestGetBackCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឈ្មោះ រឺ ពាក្យសំងាត់ដែលអ្នកបានបញ្ចូលពុំត្រឹមត្រូវទេ។ សូមមេត្តាត្រួតពិនិត្យឡើងវិញ !.
        /// </summary>
        internal static string MsgOperationRequestLogInFail {
            get {
                return ResourceManager.GetString("MsgOperationRequestLogInFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ពុំមានផលិតផលដែលអ្នកស្វែងរកទេ ។ សូមព្យាយាមម្ដងទៀត !.
        /// </summary>
        internal static string MsgOperationRequestProductNotFound {
            get {
                return ResourceManager.GetString("MsgOperationRequestProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ការប្រើប្រាស់សាកល្បងត្រូវបានបញ្ចប់។ សូមមេត្តាទាក់ទងអ្នកទទួលខុសត្រូវ។.
        /// </summary>
        internal static string MsgTrialPeriodExpire {
            get {
                return ResourceManager.GetString("MsgTrialPeriodExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ផលិតផលនេះពុំអាចលុបបានទេ។ សូមមេត្តាទាក់ទងអ្នកទទួលខុសត្រូវ៕.
        /// </summary>
        internal static string MsgUnknownError {
            get {
                return ResourceManager.GetString("MsgUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អ្នក​ពុំ​មាន​សិទ្ឋិ​គ្រប់​គ្រាន់​សំរាប់​ប្រតិបត្តិ​ការ​នេះ​ទេ ។.
        /// </summary>
        internal static string MsgUserPermissionDeny {
            get {
                return ResourceManager.GetString("MsgUserPermissionDeny", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NoImage {
            get {
                object obj = ResourceManager.GetObject("NoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OK32 {
            get {
                object obj = ResourceManager.GetObject("OK32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string OperationLogIn {
            get {
                return ResourceManager.GetString("OperationLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string OperationLogOut {
            get {
                return ResourceManager.GetString("OperationLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEL.
        /// </summary>
        internal static string OperationRequestDelete {
            get {
                return ResourceManager.GetString("OperationRequestDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPL.
        /// </summary>
        internal static string OperationRequestDuplicate {
            get {
                return ResourceManager.GetString("OperationRequestDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS.
        /// </summary>
        internal static string OperationRequestInsert {
            get {
                return ResourceManager.GetString("OperationRequestInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD.
        /// </summary>
        internal static string OperationRequestUpdate {
            get {
                return ResourceManager.GetString("OperationRequestUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string PermissionAddCard {
            get {
                return ResourceManager.GetString("PermissionAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        internal static string PermissionAddConfig {
            get {
                return ResourceManager.GetString("PermissionAddConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string PermissionAddCustomer {
            get {
                return ResourceManager.GetString("PermissionAddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string PermissionAddExpense {
            get {
                return ResourceManager.GetString("PermissionAddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string PermissionAddProduct {
            get {
                return ResourceManager.GetString("PermissionAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43.
        /// </summary>
        internal static string PermissionAddSupplier {
            get {
                return ResourceManager.GetString("PermissionAddSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string PermissionAddUser {
            get {
                return ResourceManager.GetString("PermissionAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string PermissionCard {
            get {
                return ResourceManager.GetString("PermissionCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string PermissionConfig {
            get {
                return ResourceManager.GetString("PermissionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string PermissionCustomer {
            get {
                return ResourceManager.GetString("PermissionCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string PermissionDeleteCard {
            get {
                return ResourceManager.GetString("PermissionDeleteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string PermissionDeleteConfig {
            get {
                return ResourceManager.GetString("PermissionDeleteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string PermissionDeleteCustomer {
            get {
                return ResourceManager.GetString("PermissionDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string PermissionDeleteExpense {
            get {
                return ResourceManager.GetString("PermissionDeleteExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string PermissionDeleteProduct {
            get {
                return ResourceManager.GetString("PermissionDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45.
        /// </summary>
        internal static string PermissionDeleteSupplier {
            get {
                return ResourceManager.GetString("PermissionDeleteSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string PermissionDeleteUser {
            get {
                return ResourceManager.GetString("PermissionDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string PermissionEditCard {
            get {
                return ResourceManager.GetString("PermissionEditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string PermissionEditConfig {
            get {
                return ResourceManager.GetString("PermissionEditConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string PermissionEditCustomer {
            get {
                return ResourceManager.GetString("PermissionEditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        internal static string PermissionEditExpense {
            get {
                return ResourceManager.GetString("PermissionEditExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string PermissionEditProduct {
            get {
                return ResourceManager.GetString("PermissionEditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44.
        /// </summary>
        internal static string PermissionEditSupplier {
            get {
                return ResourceManager.GetString("PermissionEditSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string PermissionEditUser {
            get {
                return ResourceManager.GetString("PermissionEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        internal static string PermissionExpense {
            get {
                return ResourceManager.GetString("PermissionExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string PermissionGetBackCard {
            get {
                return ResourceManager.GetString("PermissionGetBackCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41.
        /// </summary>
        internal static string PermissionImportExportProduct {
            get {
                return ResourceManager.GetString("PermissionImportExportProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39.
        /// </summary>
        internal static string PermissionModifyProductQuantity {
            get {
                return ResourceManager.GetString("PermissionModifyProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string PermissionPrintCardCode {
            get {
                return ResourceManager.GetString("PermissionPrintCardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string PermissionPrintProductCode {
            get {
                return ResourceManager.GetString("PermissionPrintProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string PermissionProduct {
            get {
                return ResourceManager.GetString("PermissionProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37.
        /// </summary>
        internal static string PermissionProductAdjustment {
            get {
                return ResourceManager.GetString("PermissionProductAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string PermissionReport {
            get {
                return ResourceManager.GetString("PermissionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38.
        /// </summary>
        internal static string PermissionReturnProduct {
            get {
                return ResourceManager.GetString("PermissionReturnProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string PermissionSaleOrder {
            get {
                return ResourceManager.GetString("PermissionSaleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string PermissionSpecialDiscount {
            get {
                return ResourceManager.GetString("PermissionSpecialDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.
        /// </summary>
        internal static string PermissionSupplier {
            get {
                return ResourceManager.GetString("PermissionSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string PermissionUser {
            get {
                return ResourceManager.GetString("PermissionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string PermissionViewAllProductInfo {
            get {
                return ResourceManager.GetString("PermissionViewAllProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        internal static string PermissionViewDetailStockReport {
            get {
                return ResourceManager.GetString("PermissionViewDetailStockReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        internal static string PermissionViewExpenseReport {
            get {
                return ResourceManager.GetString("PermissionViewExpenseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        internal static string PermissionViewExpiredProductReport {
            get {
                return ResourceManager.GetString("PermissionViewExpiredProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        internal static string PermissionViewReturnProductReport {
            get {
                return ResourceManager.GetString("PermissionViewReturnProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.
        /// </summary>
        internal static string PermissionViewSaleDetailReport {
            get {
                return ResourceManager.GetString("PermissionViewSaleDetailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.
        /// </summary>
        internal static string PermissionViewSaleReport {
            get {
                return ResourceManager.GetString("PermissionViewSaleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string PermissionViewStockReport {
            get {
                return ResourceManager.GetString("PermissionViewStockReport", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap pnlBodyRight {
            get {
                object obj = ResourceManager.GetObject("pnlBodyRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Printer {
            get {
                object obj = ResourceManager.GetObject("Printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Product32 {
            get {
                object obj = ResourceManager.GetObject("Product32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sale32 {
            get {
                object obj = ResourceManager.GetObject("Sale32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save32 {
            get {
                object obj = ResourceManager.GetObject("save32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search32 {
            get {
                object obj = ResourceManager.GetObject("Search32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Undo32 {
            get {
                object obj = ResourceManager.GetObject("Undo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User32 {
            get {
                object obj = ResourceManager.GetObject("User32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
