//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4963
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzPos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EzPos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add32 {
            get {
                object obj = ResourceManager.GetObject("add32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 69.
        /// </summary>
        internal static string AppParamApplicationType {
            get {
                return ResourceManager.GetString("AppParamApplicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        internal static string AppParamBarcodePrintingType {
            get {
                return ResourceManager.GetString("AppParamBarcodePrintingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        internal static string AppParamBarcodeTemplate {
            get {
                return ResourceManager.GetString("AppParamBarcodeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string AppParamCategory {
            get {
                return ResourceManager.GetString("AppParamCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string AppParamColor {
            get {
                return ResourceManager.GetString("AppParamColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string AppParamContractType {
            get {
                return ResourceManager.GetString("AppParamContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string AppParamCountry {
            get {
                return ResourceManager.GetString("AppParamCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string AppParamCourteousy {
            get {
                return ResourceManager.GetString("AppParamCourteousy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string AppParamCurrency {
            get {
                return ResourceManager.GetString("AppParamCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string AppParamDiscountType {
            get {
                return ResourceManager.GetString("AppParamDiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterLabel.
        /// </summary>
        internal static string AppParamDisplay {
            get {
                return ResourceManager.GetString("AppParamDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string AppParamExchangeRate {
            get {
                return ResourceManager.GetString("AppParamExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string AppParamExpense {
            get {
                return ResourceManager.GetString("AppParamExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string AppParamFeature {
            get {
                return ResourceManager.GetString("AppParamFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string AppParamGender {
            get {
                return ResourceManager.GetString("AppParamGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.
        /// </summary>
        internal static string AppParamIssueReceipt {
            get {
                return ResourceManager.GetString("AppParamIssueReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string AppParamMaritalStatus {
            get {
                return ResourceManager.GetString("AppParamMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string AppParamMark {
            get {
                return ResourceManager.GetString("AppParamMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string AppParamPaymentType {
            get {
                return ResourceManager.GetString("AppParamPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string AppParamPosition {
            get {
                return ResourceManager.GetString("AppParamPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string AppParamPOStatus {
            get {
                return ResourceManager.GetString("AppParamPOStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string AppParamProductCodeLength {
            get {
                return ResourceManager.GetString("AppParamProductCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string AppParamReceiptFooter {
            get {
                return ResourceManager.GetString("AppParamReceiptFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        internal static string AppParamReceiptPrinter {
            get {
                return ResourceManager.GetString("AppParamReceiptPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.
        /// </summary>
        internal static string AppParamReceiptTemplate {
            get {
                return ResourceManager.GetString("AppParamReceiptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string AppParamReportPrinter {
            get {
                return ResourceManager.GetString("AppParamReportPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        internal static string AppParamServerPhotoPath {
            get {
                return ResourceManager.GetString("AppParamServerPhotoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string AppParamShopAddress {
            get {
                return ResourceManager.GetString("AppParamShopAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        internal static string AppParamShopContact {
            get {
                return ResourceManager.GetString("AppParamShopContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string AppParamShopName {
            get {
                return ResourceManager.GetString("AppParamShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string AppParamSize {
            get {
                return ResourceManager.GetString("AppParamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string AppParamSkin {
            get {
                return ResourceManager.GetString("AppParamSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterId.
        /// </summary>
        internal static string AppParamValue {
            get {
                return ResourceManager.GetString("AppParamValue", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap b_drop {
            get {
                object obj = ResourceManager.GetObject("b_drop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backgroud_11 {
            get {
                object obj = ResourceManager.GetObject("backgroud_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backgroud_12 {
            get {
                object obj = ResourceManager.GetObject("backgroud_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background_16 {
            get {
                object obj = ResourceManager.GetObject("background_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background_2 {
            get {
                object obj = ResourceManager.GetObject("background_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background_5 {
            get {
                object obj = ResourceManager.GetObject("background_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap background_9 {
            get {
                object obj = ResourceManager.GetObject("background_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Buy32 {
            get {
                object obj = ResourceManager.GetObject("Buy32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel32 {
            get {
                object obj = ResourceManager.GetObject("Cancel32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Config32 {
            get {
                object obj = ResourceManager.GetObject("Config32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ConstAmountZeroOneDigit {
            get {
                return ResourceManager.GetString("ConstAmountZeroOneDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.000.
        /// </summary>
        internal static string ConstAmountZeroThreeDigits {
            get {
                return ResourceManager.GetString("ConstAmountZeroThreeDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00.
        /// </summary>
        internal static string ConstAmountZeroTwoDigits {
            get {
                return ResourceManager.GetString("ConstAmountZeroTwoDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to barcode.xlsx.
        /// </summary>
        internal static string ConstBarcodeExcelFile {
            get {
                return ResourceManager.GetString("ConstBarcodeExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 1.
        /// </summary>
        internal static string ConstBarCodeTemplate1 {
            get {
                return ResourceManager.GetString("ConstBarCodeTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 2.
        /// </summary>
        internal static string ConstBarCodeTemplate2 {
            get {
                return ResourceManager.GetString("ConstBarCodeTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 3.
        /// </summary>
        internal static string ConstBarCodeTemplate3 {
            get {
                return ResourceManager.GetString("ConstBarCodeTemplate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 4.
        /// </summary>
        internal static string ConstBarCodeTemplate4 {
            get {
                return ResourceManager.GetString("ConstBarCodeTemplate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 5.
        /// </summary>
        internal static string ConstBarCodeTemplate5 {
            get {
                return ResourceManager.GetString("ConstBarCodeTemplate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConstBarCodeTemplate6 {
            get {
                return ResourceManager.GetString("ConstBarCodeTemplate6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string ConstCloseBracket {
            get {
                return ResourceManager.GetString("ConstCloseBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string ConstCurrencyDollar {
            get {
                return ResourceManager.GetString("ConstCurrencyDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string ConstCurrencyRiel {
            get {
                return ResourceManager.GetString("ConstCurrencyRiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConstDeposit {
            get {
                return ResourceManager.GetString("ConstDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice-deposit.xlsx.
        /// </summary>
        internal static string ConstDepositExcelFile {
            get {
                return ResourceManager.GetString("ConstDepositExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConstDepositItem {
            get {
                return ResourceManager.GetString("ConstDepositItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pictures|*.bmp;*.gif;*.jpg|Bitmaps|*.bmp|GIFs|*.gif|JPEGs|*.jpg.
        /// </summary>
        internal static string ConstExtensionImage {
            get {
                return ResourceManager.GetString("ConstExtensionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConstFileName {
            get {
                return ResourceManager.GetString("ConstFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConstFolderName {
            get {
                return ResourceManager.GetString("ConstFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to income statement.xlsx.
        /// </summary>
        internal static string ConstIncomeStatementExcelFile {
            get {
                return ResourceManager.GetString("ConstIncomeStatementExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string ConstOpenBracket {
            get {
                return ResourceManager.GetString("ConstOpenBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ .
        /// </summary>
        internal static string ConstPrefixDollar {
            get {
                return ResourceManager.GetString("ConstPrefixDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R .
        /// </summary>
        internal static string ConstPrefixRiel {
            get {
                return ResourceManager.GetString("ConstPrefixRiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConstProductAdjustment {
            get {
                return ResourceManager.GetString("ConstProductAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConstProductList {
            get {
                return ResourceManager.GetString("ConstProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ចំនួនសរុបនៃផលិតផលដែលបានទិញ៖ .
        /// </summary>
        internal static string ConstPurchaseInfoPrefix {
            get {
                return ResourceManager.GetString("ConstPurchaseInfoPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 1.
        /// </summary>
        internal static string ConstReceiptTemplate1 {
            get {
                return ResourceManager.GetString("ConstReceiptTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 2.
        /// </summary>
        internal static string ConstReceiptTemplate2 {
            get {
                return ResourceManager.GetString("ConstReceiptTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 3.
        /// </summary>
        internal static string ConstReceiptTemplate3 {
            get {
                return ResourceManager.GetString("ConstReceiptTemplate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ម្ដង​ទៀត.
        /// </summary>
        internal static string ConstRepeatSearch {
            get {
                return ResourceManager.GetString("ConstRepeatSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConstRequestOperation {
            get {
                return ResourceManager.GetString("ConstRequestOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice-sale.xlsx.
        /// </summary>
        internal static string ConstSaleExcelFile {
            get {
                return ResourceManager.GetString("ConstSaleExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to គិតលុយ.
        /// </summary>
        internal static string ConstSalePay {
            get {
                return ResourceManager.GetString("ConstSalePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to បោះពុម្ភ.
        /// </summary>
        internal static string ConstSalePrint {
            get {
                return ResourceManager.GetString("ConstSalePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សង.
        /// </summary>
        internal static string ConstSaleReturn {
            get {
                return ResourceManager.GetString("ConstSaleReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ស្វែងរក.
        /// </summary>
        internal static string ConstSaleSearch {
            get {
                return ResourceManager.GetString("ConstSaleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConstSearchCriteria {
            get {
                return ResourceManager.GetString("ConstSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string ConstSheetBarcode {
            get {
                return ResourceManager.GetString("ConstSheetBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Statement.
        /// </summary>
        internal static string ConstSheetIncomeStatement {
            get {
                return ResourceManager.GetString("ConstSheetIncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string ConstSheetInvoice {
            get {
                return ResourceManager.GetString("ConstSheetInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ConstSheetReceipt {
            get {
                return ResourceManager.GetString("ConstSheetReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string ConstSheetStockStatement {
            get {
                return ResourceManager.GetString("ConstSheetStockStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stock statement.xlsx.
        /// </summary>
        internal static string ConstStockStatementExcelFile {
            get {
                return ResourceManager.GetString("ConstStockStatementExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string ConstSuffixPercentage {
            get {
                return ResourceManager.GetString("ConstSuffixPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r.
        /// </summary>
        internal static string ConstTextBreak {
            get {
                return ResourceManager.GetString("ConstTextBreak", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Customer32 {
            get {
                object obj = ResourceManager.GetObject("Customer32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete32 {
            get {
                object obj = ResourceManager.GetObject("Delete32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit32 {
            get {
                object obj = ResourceManager.GetObject("exit32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail customer.
        /// </summary>
        internal static string ModCustomer {
            get {
                return ResourceManager.GetString("ModCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string ModDeposit {
            get {
                return ResourceManager.GetString("ModDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount card.
        /// </summary>
        internal static string ModDiscountCard {
            get {
                return ResourceManager.GetString("ModDiscountCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string MsgCaptionConfirm {
            get {
                return ResourceManager.GetString("MsgCaptionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MsgCaptionError {
            get {
                return ResourceManager.GetString("MsgCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MsgCaptionInformation {
            get {
                return ResourceManager.GetString("MsgCaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string MsgCaptionUnknownError {
            get {
                return ResourceManager.GetString("MsgCaptionUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទឹកប្រាក់ដែលអ្នកបានបញ្ចូលពុំទាន់គ្រប់គ្រាន់ទេ ។ តើអ្នកពិតជាចង់បន្តដំណើរការទៀត?.
        /// </summary>
        internal static string MsgConfirmCreditPayment {
            get {
                return ResourceManager.GetString("MsgConfirmCreditPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមមេត្តាចុចលើប៊ូតុងយល់ព្រមដើម្បីប្រគល់ទំនិញទៅ អោយអតិថិជន ។.
        /// </summary>
        internal static string MsgConfirmDeliverProduct {
            get {
                return ResourceManager.GetString("MsgConfirmDeliverProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ផលិតផលដូចគ្នានឹងលេខកូដនេះត្រូវបានរកឃើញ​។ តើអ្នកចង់កែប្រែពត៌មាននៃផលិតផលដែលបានរកឃើញ?.
        /// </summary>
        internal static string MsgConfirmEditExistingProduct {
            get {
                return ResourceManager.GetString("MsgConfirmEditExistingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទំនាក់ទំនងជាមួយម៉ាស៊ីនមេ ត្រូវបានកាត់ផ្ដាច់។ សូម​មេត្តា​ទាក់ទង​​ជាមួយ​អ្នក​ទទួល​ខុស​ត្រូវ​៕.
        /// </summary>
        internal static string MsgConnectionLost {
            get {
                return ResourceManager.GetString("MsgConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ម៉ាស៊ីន​នេះ​មិន​មាន​សិទ្ឋិ​ចូល​ទៅ​ក្នុង​ប្រព័ន្ឋ​ទេ​។ សូម​មេត្តា​ទាក់ទង​​ជាមួយ​អ្នក​ទទួល​ខុស​ត្រូវ​៕.
        /// </summary>
        internal static string MsgCounterNotInitialize {
            get {
                return ResourceManager.GetString("MsgCounterNotInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert empty BindingList to List.
        /// </summary>
        internal static string MsgEmptyBindingList {
            get {
                return ResourceManager.GetString("MsgEmptyBindingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to លេខកូដផលិតផលដែលបានបញ្ចូលពុំត្រឹមត្រូវទេ។ សូមមេត្តាត្រួតពិនិត្យឡើងវិញ !.
        /// </summary>
        internal static string MsgExceedProductCodeLength {
            get {
                return ResourceManager.GetString("MsgExceedProductCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid paramter..
        /// </summary>
        internal static string MsgInvalidAppParameter {
            get {
                return ResourceManager.GetString("MsgInvalidAppParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ពត៌មានដែលអ្នកបានបញ្ចូលពុំត្រឹមត្រូវ។ សូមមេត្តាត្រួតពិនិត្យឡើងវិញ !.
        /// </summary>
        internal static string MsgInvalidData {
            get {
                return ResourceManager.GetString("MsgInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid deposit..
        /// </summary>
        internal static string MsgInvalidDeposit {
            get {
                return ResourceManager.GetString("MsgInvalidDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ទឹកប្រាក់កក់ពុំអាចស្មើ រឺលើសនឹងទឹកប្រាក់សរុបឡើយ។.
        /// </summary>
        internal static string MsgInvalidDepositPayment {
            get {
                return ResourceManager.GetString("MsgInvalidDepositPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid exchange rate..
        /// </summary>
        internal static string MsgInvalidExchangeRate {
            get {
                return ResourceManager.GetString("MsgInvalidExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expense..
        /// </summary>
        internal static string MsgInvalidExpense {
            get {
                return ResourceManager.GetString("MsgInvalidExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder path..
        /// </summary>
        internal static string MsgInvalidFolderPath {
            get {
                return ResourceManager.GetString("MsgInvalidFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string MsgInvalidInput {
            get {
                return ResourceManager.GetString("MsgInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid product..
        /// </summary>
        internal static string MsgInvalidProduct {
            get {
                return ResourceManager.GetString("MsgInvalidProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        internal static string MsgInvalidRequest {
            get {
                return ResourceManager.GetString("MsgInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sale item..
        /// </summary>
        internal static string MsgInvalidSaleItem {
            get {
                return ResourceManager.GetString("MsgInvalidSaleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sale order..
        /// </summary>
        internal static string MsgInvalidSaleOrder {
            get {
                return ResourceManager.GetString("MsgInvalidSaleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid search criteria..
        /// </summary>
        internal static string MsgInvalidSearchCriteria {
            get {
                return ResourceManager.GetString("MsgInvalidSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមអភ័យទោស ផលិតផលនេះពុំអាចលក់ជូនក្នុងតំលៃនេះបានទេ។ សូមមេត្តាព្យាយាម្ដងទៀតជាមួយតំលៃដែលខ្ពស់ជាងនេះ៕.
        /// </summary>
        internal static string MsgInvalidUnitPriceOut {
            get {
                return ResourceManager.GetString("MsgInvalidUnitPriceOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item specified does not exist in the list..
        /// </summary>
        internal static string MsgItemNotInList {
            get {
                return ResourceManager.GetString("MsgItemNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to របាយការណ៏គំរូបានបាត់ចេញពីប្រព័ន្ឋ។ សូមទាក់ទងអ្នកទទួលខុសត្រូវដើម្បីព៌តមានបន្ថែម។.
        /// </summary>
        internal static string MsgMissingIncomeStatement {
            get {
                return ResourceManager.GetString("MsgMissingIncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អ្នកកំពុងព្យាយាមយកផលិតផលមួយចំនួនទៅដាក់ក្នុងស្តុក។ ប្រតិបត្តិការនេះអាចនឹងចំណាយពេលយូរ ៕.
        /// </summary>
        internal static string MsgOperationImportGroupCatalog {
            get {
                return ResourceManager.GetString("MsgOperationImportGroupCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូម​មេត្តា​ចុច​លើ​ប៊ូតុង យល់​ព្រម ដើម្បី​បញ្ជាក់​អំពី​សំណើរ​បោះ​បង់​របស់​អ្នក ។.
        /// </summary>
        internal static string MsgOperationRequestCancel {
            get {
                return ResourceManager.GetString("MsgOperationRequestCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ពុំមានអតិថិជនដែលអ្នកស្វែងរកទេ ។ សូមព្យាយាមម្ដងទៀត !.
        /// </summary>
        internal static string MsgOperationRequestCustomerNotFound {
            get {
                return ResourceManager.GetString("MsgOperationRequestCustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to តើអ្នកពិតជាចង់លុប .
        /// </summary>
        internal static string MsgOperationRequestDelete {
            get {
                return ResourceManager.GetString("MsgOperationRequestDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូម​មេត្តា​ចុច​លើ​ប៊ូតុង យល់​ព្រម ដើម្បី​ដក​ហូត​ប័ណ្ណ​បញ្ចុះ​តំលៃ​ពី .
        /// </summary>
        internal static string MsgOperationRequestGetBackCard {
            get {
                return ResourceManager.GetString("MsgOperationRequestGetBackCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឈ្មោះ រឺ ពាក្យសំងាត់ដែលអ្នកបានបញ្ចូលពុំត្រឹមត្រូវទេ។ សូមមេត្តាត្រួតពិនិត្យឡើងវិញ !.
        /// </summary>
        internal static string MsgOperationRequestLogInFail {
            get {
                return ResourceManager.GetString("MsgOperationRequestLogInFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ពុំមានផលិតផលដែលអ្នកស្វែងរកទេ ។ សូមព្យាយាមម្ដងទៀត !.
        /// </summary>
        internal static string MsgOperationRequestProductNotFound {
            get {
                return ResourceManager.GetString("MsgOperationRequestProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown request.
        /// </summary>
        internal static string MsgOperationRequestUnknown {
            get {
                return ResourceManager.GetString("MsgOperationRequestUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ការប្រើប្រាស់សាកល្បងត្រូវបានបញ្ចប់។ សូមមេត្តាទាក់ទងអ្នកទទួលខុសត្រូវ។.
        /// </summary>
        internal static string MsgTrialPeriodExpire {
            get {
                return ResourceManager.GetString("MsgTrialPeriodExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ផលិតផលនេះពុំអាចលុបបានទេ។ សូមមេត្តាទាក់ទងអ្នកទទួលខុសត្រូវ៕.
        /// </summary>
        internal static string MsgUnknownError {
            get {
                return ResourceManager.GetString("MsgUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request code.
        /// </summary>
        internal static string MsgUnknownRequestCode {
            get {
                return ResourceManager.GetString("MsgUnknownRequestCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to អ្នក​ពុំ​មាន​សិទ្ឋិ​គ្រប់​គ្រាន់​សំរាប់​ប្រតិបត្តិ​ការ​នេះ​ទេ ។.
        /// </summary>
        internal static string MsgUserPermissionDeny {
            get {
                return ResourceManager.GetString("MsgUserPermissionDeny", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NoImage {
            get {
                object obj = ResourceManager.GetObject("NoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OK32 {
            get {
                object obj = ResourceManager.GetObject("OK32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string OperationLogIn {
            get {
                return ResourceManager.GetString("OperationLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string OperationLogOut {
            get {
                return ResourceManager.GetString("OperationLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEL.
        /// </summary>
        internal static string OperationRequestDelete {
            get {
                return ResourceManager.GetString("OperationRequestDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPL.
        /// </summary>
        internal static string OperationRequestDuplicate {
            get {
                return ResourceManager.GetString("OperationRequestDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS.
        /// </summary>
        internal static string OperationRequestInsert {
            get {
                return ResourceManager.GetString("OperationRequestInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPD.
        /// </summary>
        internal static string OperationRequestUpdate {
            get {
                return ResourceManager.GetString("OperationRequestUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string PermissionAddCard {
            get {
                return ResourceManager.GetString("PermissionAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        internal static string PermissionAddConfig {
            get {
                return ResourceManager.GetString("PermissionAddConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string PermissionAddCustomer {
            get {
                return ResourceManager.GetString("PermissionAddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47.
        /// </summary>
        internal static string PermissionAddDeposit {
            get {
                return ResourceManager.GetString("PermissionAddDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string PermissionAddExpense {
            get {
                return ResourceManager.GetString("PermissionAddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string PermissionAddProduct {
            get {
                return ResourceManager.GetString("PermissionAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43.
        /// </summary>
        internal static string PermissionAddSupplier {
            get {
                return ResourceManager.GetString("PermissionAddSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string PermissionAddUser {
            get {
                return ResourceManager.GetString("PermissionAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59.
        /// </summary>
        internal static string PermissionByDatesReport {
            get {
                return ResourceManager.GetString("PermissionByDatesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49.
        /// </summary>
        internal static string PermissionCancelDeposit {
            get {
                return ResourceManager.GetString("PermissionCancelDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string PermissionCard {
            get {
                return ResourceManager.GetString("PermissionCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52.
        /// </summary>
        internal static string PermissionChangeExpenseDate {
            get {
                return ResourceManager.GetString("PermissionChangeExpenseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string PermissionConfig {
            get {
                return ResourceManager.GetString("PermissionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string PermissionCustomer {
            get {
                return ResourceManager.GetString("PermissionCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string PermissionDeleteCard {
            get {
                return ResourceManager.GetString("PermissionDeleteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string PermissionDeleteConfig {
            get {
                return ResourceManager.GetString("PermissionDeleteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string PermissionDeleteCustomer {
            get {
                return ResourceManager.GetString("PermissionDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string PermissionDeleteExpense {
            get {
                return ResourceManager.GetString("PermissionDeleteExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string PermissionDeleteProduct {
            get {
                return ResourceManager.GetString("PermissionDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45.
        /// </summary>
        internal static string PermissionDeleteSupplier {
            get {
                return ResourceManager.GetString("PermissionDeleteSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string PermissionDeleteUser {
            get {
                return ResourceManager.GetString("PermissionDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string PermissionEditCard {
            get {
                return ResourceManager.GetString("PermissionEditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string PermissionEditConfig {
            get {
                return ResourceManager.GetString("PermissionEditConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string PermissionEditCustomer {
            get {
                return ResourceManager.GetString("PermissionEditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48.
        /// </summary>
        internal static string PermissionEditDeposit {
            get {
                return ResourceManager.GetString("PermissionEditDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        internal static string PermissionEditExpense {
            get {
                return ResourceManager.GetString("PermissionEditExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string PermissionEditProduct {
            get {
                return ResourceManager.GetString("PermissionEditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44.
        /// </summary>
        internal static string PermissionEditSupplier {
            get {
                return ResourceManager.GetString("PermissionEditSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string PermissionEditUser {
            get {
                return ResourceManager.GetString("PermissionEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        internal static string PermissionExpense {
            get {
                return ResourceManager.GetString("PermissionExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51.
        /// </summary>
        internal static string PermissionGetBackCard {
            get {
                return ResourceManager.GetString("PermissionGetBackCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41.
        /// </summary>
        internal static string PermissionImportExportProduct {
            get {
                return ResourceManager.GetString("PermissionImportExportProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39.
        /// </summary>
        internal static string PermissionModifyProductQuantity {
            get {
                return ResourceManager.GetString("PermissionModifyProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string PermissionPrintCardCode {
            get {
                return ResourceManager.GetString("PermissionPrintCardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string PermissionPrintProductCode {
            get {
                return ResourceManager.GetString("PermissionPrintProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string PermissionProduct {
            get {
                return ResourceManager.GetString("PermissionProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37.
        /// </summary>
        internal static string PermissionProductAdjustment {
            get {
                return ResourceManager.GetString("PermissionProductAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string PermissionReport {
            get {
                return ResourceManager.GetString("PermissionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38.
        /// </summary>
        internal static string PermissionReturnProduct {
            get {
                return ResourceManager.GetString("PermissionReturnProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string PermissionSaleOrder {
            get {
                return ResourceManager.GetString("PermissionSaleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string PermissionSpecialDiscount {
            get {
                return ResourceManager.GetString("PermissionSpecialDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.
        /// </summary>
        internal static string PermissionSupplier {
            get {
                return ResourceManager.GetString("PermissionSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string PermissionUser {
            get {
                return ResourceManager.GetString("PermissionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string PermissionViewAllProductInfo {
            get {
                return ResourceManager.GetString("PermissionViewAllProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        internal static string PermissionViewCartResultInfo {
            get {
                return ResourceManager.GetString("PermissionViewCartResultInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58.
        /// </summary>
        internal static string PermissionViewCustResultInfo {
            get {
                return ResourceManager.GetString("PermissionViewCustResultInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string PermissionViewDepositReport {
            get {
                return ResourceManager.GetString("PermissionViewDepositReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        internal static string PermissionViewDetailStockReport {
            get {
                return ResourceManager.GetString("PermissionViewDetailStockReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        internal static string PermissionViewExpenseReport {
            get {
                return ResourceManager.GetString("PermissionViewExpenseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        internal static string PermissionViewExpiredProductReport {
            get {
                return ResourceManager.GetString("PermissionViewExpiredProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 57.
        /// </summary>
        internal static string PermissionViewExpResultInfo {
            get {
                return ResourceManager.GetString("PermissionViewExpResultInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53.
        /// </summary>
        internal static string PermissionViewIncomeStatementReport {
            get {
                return ResourceManager.GetString("PermissionViewIncomeStatementReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54.
        /// </summary>
        internal static string PermissionViewProdResultInfo {
            get {
                return ResourceManager.GetString("PermissionViewProdResultInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        internal static string PermissionViewReturnProductReport {
            get {
                return ResourceManager.GetString("PermissionViewReturnProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.
        /// </summary>
        internal static string PermissionViewSaleDetailReport {
            get {
                return ResourceManager.GetString("PermissionViewSaleDetailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.
        /// </summary>
        internal static string PermissionViewSaleReport {
            get {
                return ResourceManager.GetString("PermissionViewSaleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string PermissionViewStockReport {
            get {
                return ResourceManager.GetString("PermissionViewStockReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 56.
        /// </summary>
        internal static string PermissionViewSuppResultInfo {
            get {
                return ResourceManager.GetString("PermissionViewSuppResultInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        internal static string PermissionViewUserResultInfo {
            get {
                return ResourceManager.GetString("PermissionViewUserResultInfo", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap pnlBodyRight {
            get {
                object obj = ResourceManager.GetObject("pnlBodyRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Printer {
            get {
                object obj = ResourceManager.GetObject("Printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Product32 {
            get {
                object obj = ResourceManager.GetObject("Product32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sale32 {
            get {
                object obj = ResourceManager.GetObject("Sale32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save32 {
            get {
                object obj = ResourceManager.GetObject("save32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search32 {
            get {
                object obj = ResourceManager.GetObject("Search32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Undo32 {
            get {
                object obj = ResourceManager.GetObject("Undo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User32 {
            get {
                object obj = ResourceManager.GetObject("User32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
